### ISSUE TITLE
::Client not playing nice with std::optional copy constructor

### ISSUE THREAD

**Issue by germandiagogomez** [capnproto/capnproto#920] opened 2019-12-22 13:05 UTC
It seems that capnproto types use defaulted assignment and copy constructors that are non-const.

This creates the problem that when I try to use some code like this, it fails:

```c++
std::optional<My::CapnpClass::Client> c_;
...

c_ = ctx.getParams.getCapnpClass(); //getCapnpClass is marked as const.
```

Since optional tries to copy and CapnpClass has no const copy constructor, this is failing with the following error:

```
'this' argument has type 'const std::optional<Subscriber<RoomInfo>::Client>', but method is not marked const
```

**Comment by kentonv** [comment] 2019-12-22 18:19
Hi Germán,

In general, KJ-style code tries to enforce transitive constness. This is necessary in particular in order for `const` to be a useful way to catch thread-safety bugs. The language actually supports a notion of copy constructors that only accept a non-const reference, and KJ commonly uses these to enforce that you can't de-const transitive references held by an object just by shallow-copying it.

Unfortunately, despite having some support, `const` wasn't really designed to be transitive, and the C++ standard library especially wasn't really designed with this use of `const` in mind.

The problem here actually isn't `getCapnpClass()`'s `const`ness -- that has no bearing on what it returns. The problem is in `std::optional` -- it is apparently not designed to account for types that use non-const copy constructors.

Could you try using `kj::Maybe<My::CapnpClass::Client>` instead? It is very similar to `std::optional` but doesn't have this bug. `kj::Maybe` also features a design that doesn't let you access the contained value without first checking if it is present (you use the `KJ_IF_MAYBE` macro to unwrap it).

**Comment by germandiagogomez** [comment] 2019-12-22 20:22
Hello @kentonv 

Thanks. Using `kj::Maybe` is a solution that would somewhat work for me. For now I changed to using a `std::shared_ptr` and I do not like that it allocates. OTOH,  I think since this is server-side and anyway I am going to use Capnproto for the server, I will change to `kj::Maybe` to avoid uneeded allocations.

**Comment by kentonv** [comment] 2020-01-07 15:40
Closing because this seems like a bug in `std::optional` which we probably can't do anything about.

**Closed by kentonv** 2020-01-07 15:40 UTC

**Comment by fvannee** [comment] 2020-04-04 15:41
Is this really a bug in `std::optional`? It's also not possible to store Client's inside `std::pair` and because of that also not in `std::unordered_map` and `std::map`. This is really annoying to be honest. What's the downside of declaring the copy constructors taking a `const` ref?

I'd like to keep a `unordered_map` of some id and client rpc objects. Eg

```
std::unordered_map<int, SomeInterface::Client>map
```

This receives a compile time error identical to the post above.
Wouldn't it make more sense to define the ref counting objects on the hook mutable or something like that (I see the `const` was omitted in all these copy constructors because it needs to get a new `kj::Own` of the client hook)

**Comment by fvannee** [comment] 2020-04-04 16:00
My alternative now is to separately store the `SomeInterface::Client` somewhere just so it's kept alive and store `map<int, SomeInterface::Client*>` instead, but this is really ugly of course.

Better alternative seems to be defining a wrapper that defines the const copy constructor. Not ideal either, but workable..

```

	template <typename T>
	class Wrapper
	{
	public:
		Wrapper(T t) : mT(std::move(t)) {}
		Wrapper(const Wrapper& other) : mT(other.mT) {}
		Wrapper(Wrapper&&) = default;
		Wrapper& operator=(const Wrapper& other)
		{
			mT = other.mT;
		}
		Wrapper& operator=(Wrapper&& other) = default;

		T& get() { return mT; }
		const T& get() const { return mT; }

	private:
		T mT;
	};
```

**Comment by kentonv** [comment] 2020-04-04 16:42
Hi Floris,

In KJ style, we expect that anything marked `const` is safe to use across threads. If you can trivially remove the constness by shallow-copying an object then that property goes out the window, unfortunately.

The wrapper doesn't actually have to implement const copy -- it just has to _delete_ the non-const copy, which convinces the standard library to use move semantics instead. Incidentally, this is probably what you want in practice because it's much faster!

So a wrapper like this works:

    template <typename T>
    struct Wrapper {
      T value;
      Wrapper(Wrapper&&) = default;
      Wrapper(Wrapper&) = delete;
      Wrapper& operator=(Wrapper&&) = default;
      Wrapper& operator=(Wrapper&) = delete;
    }

Another option is to use `kj::HashMap` which doesn't have this problem.

**Comment by fvannee** [comment] 2020-04-04 19:07
Ah thanks! Yes, that works too. Although I needed to delete the const copy constructor, rather than the non-const version. Otherwise I ended up with the same error.

**Comment by kentonv** [comment] 2020-04-05 14:13
Oops, indeed, I always forget which constructor needs to be deleted.
