### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by alaindargelas** [capnproto/capnproto#1269] opened 2021-06-28 06:55 UTC
GNU 10.2.0

FAILED: third_party/UHDM/third_party/capnproto/c++/src/kj/CMakeFiles/kj.dir/exception.c++.o 
/usr/bin/g++.exe   -O3 -DNDEBUG -Wall -Wextra -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -pthread -MD -MT third_party/UHDM/third_party/capnproto/c++/src/kj/CMakeFiles/kj.dir/exception.c++.o -MF third_party/UHDM/third_party/capnproto/c++/src/kj/CMakeFiles/kj.dir/exception.c++.o.d -o third_party/UHDM/third_party/capnproto/c++/src/kj/CMakeFiles/kj.dir/exception.c++.o -c ../third_party/UHDM/third_party/capnproto/c++/src/kj/exception.c++
In file included from ../third_party/UHDM/third_party/capnproto/c++/src/kj/memory.h:24,
                 from ../third_party/UHDM/third_party/capnproto/c++/src/kj/exception.h:24,
                 from ../third_party/UHDM/third_party/capnproto/c++/src/kj/exception.c++:37:
../third_party/UHDM/third_party/capnproto/c++/src/kj/exception.c++:93:8: error: attributes are not allowed on a function-definition
   93 | static KJ_ALWAYS_INLINE(void __lsan_ignore_object(const void* p)) {}
      |        ^~~~~~~~~~~~~~~~

**Comment by kentonv** [comment] 2021-06-28 14:08
Duplicate of #1268.

**Closed by kentonv** 2021-06-28 14:08 UTC
