### ISSUE TITLE
Broken `json:binary` test on Ubuntu Focal (20.04) s390x

### ISSUE THREAD

**Issue by Saviq** [capnproto/capnproto#962] opened 2020-04-01 11:38 UTC
We [had a build failure](https://launchpadlibrarian.net/471777379/buildlog_ubuntu-focal-s390x.capnproto_0.7.0-5build1_BUILDING.txt.gz) of capnp-0.7.0 on s390x on Ubuntu Focal (upcoming 20.04):

```
make check-TESTS
make[4]: Entering directory '/<<PKGBUILDDIR>>'
make[5]: Entering directory '/<<PKGBUILDDIR>>'
FAIL: src/capnp/compiler/capnp-test.sh
PASS: capnp-evolution-test
PASS: capnp-test
========================================
   Capn Proto 0.7.0: ./test-suite.log
========================================

# TOTAL: 3
# PASS: 2
# SKIP: 0
# XFAIL: 0
# FAIL: 1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: src/capnp/compiler/capnp-test.sh
======================================

/<<PKGBUILDDIR>>/.libs/capnp convert: The input is not in "json" format. It looks like it is in "json" format. Try that instead.
Try '/<<PKGBUILDDIR>>/.libs/capnp convert --help' for more information.
cmp: EOF on - which is empty
FAILED: annotated json to binary
FAIL src/capnp/compiler/capnp-test.sh (exit status: 1)

============================================================================
Testsuite summary for Capn Proto 0.7.0
============================================================================
# TOTAL: 3
# PASS: 2
# SKIP: 0
# XFAIL: 0
# FAIL: 1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to capnproto@googlegroups.com
============================================================================
```

I was able to reproduce manually:
```console
$ ./capnp convert json:binary src/capnp/compiler/../compat/json-test.capnp TestJsonAnnotations -Isrc/capnp/compiler/../.. < ./src/capnp/testdata/annotated.json 
/root/capnproto-0.7.0/.libs/capnp convert: The input is not in "json" format. It looks like it is in "json" format. Try that instead.
Try '/root/capnproto-0.7.0/.libs/capnp convert --help' for more information.
```

But unsure how to proceed? The reverse test is fine:
```console
$ ./capnp convert binary:json src/capnp/compiler/../compat/json-test.capnp TestJsonAnnotations -Isrc/capnp/compiler/../.. < ./src/capnp/testdata/annotated-json.binary | cmp src/capnp/testdata/annotated.json
```

**Comment by kentonv** [comment] 2020-04-01 13:39
This is a duplicate of #754. Embarrassingly, that was fixed by #761 more than a year ago, but I haven't had a chance to do a release in the meantime. Ugh...

**Closed** 2020-04-22 17:22 UTC
